version: 2.1


executors:
  base:
    docker:
      - image: circleci/node:12.13.0

commands:
  install_node_modules:
    parameters:
      executor:
        type: string
    steps:
      - restore_cache:
          name: Restore npm cache
          key: << parameters.executor >>-npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save npm cache
          key: << parameters.executor >>-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

jobs:
  build:
    executor: base
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - install_node_modules:
          executor: build
      - run:
          name: Pre-requisites
          command: sudo apt-get install libusb-1.0-0-dev
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish_release:
    executor: base
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish release
          command: npm run release

workflows:
  version: 2
  ci:
    jobs:
      - build
      - publish_release:
          requires:
            - build
          filters:
            branches:
              only:
                - master